<?php

declare(strict_types=1);

/**
 * Creates four idempotent YOOtheme Builder catalogue demos from the products
 * generated by tools/seed-large-demo-catalog.php.
 *
 * Run from the host repository root:
 *   docker compose exec -T app php /dev/stdin < tools/seed-catalog-mode-demos.php
 */
final class CatalogModeDemoSeeder
{
    private const ARTICLE_CATEGORY_ID = 2;
    private const CREATED_BY = 42;

    private PDO $db;
    private string $now;
    private array $products = [];

    public function __construct()
    {
        $host = getenv('JOOMLA_DB_HOST') ?: 'db';
        $name = getenv('JOOMLA_DB_NAME') ?: 'database';
        $user = getenv('JOOMLA_DB_USER') ?: 'joomla';
        $pass = getenv('JOOMLA_DB_PASSWORD') ?: '';

        $this->db = new PDO(
            "mysql:host={$host};dbname={$name};charset=utf8mb4",
            $user,
            $pass,
            [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES => false,
            ]
        );
        $this->now = gmdate('Y-m-d H:i:s');
    }

    public function run(): void
    {
        $this->products = $this->loadProducts();
        if (count($this->products) < 8) {
            throw new RuntimeException(
                'The large demo catalogue is missing. Run tools/seed-large-demo-catalog.php first.'
            );
        }

        $pages = [
            'ytdynamics-catalog-layouts' => [
                'title' => 'Каталоги на элементах YTDynamics',
                'menu' => 'CATALOG LAYOUTS',
                'layout' => $this->landingLayout(),
            ],
            'ytdynamics-catalog-tile' => [
                'title' => 'Каталог · крупная плитка',
                'menu' => 'CATALOG TILE',
                'layout' => $this->modeLayout(
                    'Крупная плитка',
                    'Карточка с постоянной областью и независимой панелью вариантов, покупки и быстрого просмотра.',
                    $this->tileCatalogue()
                ),
            ],
            'ytdynamics-catalog-compact' => [
                'title' => 'Каталог · компактная плитка',
                'menu' => 'CATALOG COMPACT',
                'layout' => $this->modeLayout(
                    'Компактная плитка',
                    'Плотная витрина: до пяти карточек в строке, короткий набор данных и постоянные действия.',
                    $this->compactCatalogue()
                ),
            ],
            'ytdynamics-catalog-list' => [
                'title' => 'Каталог · строки',
                'menu' => 'CATALOG LIST',
                'layout' => $this->modeLayout(
                    'Строчное представление',
                    'Изображение, описание, характеристики, варианты и покупка собраны стандартными колонками Builder.',
                    $this->listCatalogue()
                ),
            ],
            'ytdynamics-catalog-price' => [
                'title' => 'Каталог · прайс',
                'menu' => 'CATALOG PRICE',
                'layout' => $this->modeLayout(
                    'Прайс-таблица',
                    'Семантическая RM Table с вложенными товарными элементами и карточками на мобильном.',
                    $this->priceCatalogue()
                ),
            ],
        ];

        $result = [];
        $this->db->beginTransaction();
        try {
            foreach ($pages as $alias => $page) {
                $articleId = $this->upsertArticle($alias, $page['title'], $page['layout']);
                $this->upsertMenu($alias, $page['menu'], $articleId);
                $result[$alias] = '/index.php/' . $alias;
            }
            $this->db->commit();
        } catch (Throwable $error) {
            $this->db->rollBack();
            throw $error;
        }

        echo json_encode(
            ['status' => 'ok', 'products' => count($this->products), 'pages' => $result],
            JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR
        ) . PHP_EOL;
    }

    private function loadProducts(): array
    {
        $sql = <<<'SQL'
SELECT p.id,
       p.title,
       p.alias,
       p.code,
       p.meta_variability,
       c.title AS category_title
FROM joom_radicalmart_products AS p
INNER JOIN (
    SELECT meta_variability, MIN(id) AS product_id
    FROM joom_radicalmart_products
    WHERE alias LIKE 'mega-demo-%' AND meta_variability > 0 AND state = 1
    GROUP BY meta_variability
) AS selected ON selected.product_id = p.id
LEFT JOIN joom_radicalmart_categories AS c ON c.id = p.category
ORDER BY c.id, p.id
LIMIT 12
SQL;

        return $this->query($sql)->fetchAll();
    }

    private function landingLayout(): array
    {
        $modes = [
            ['Крупная плитка', 'Изображение, цена и наличие постоянно; варианты и действия появляются отдельной панелью.', 'ytdynamics-catalog-tile', 'grid'],
            ['Компактная плитка', 'Плотная сетка без скрытой области — подходит для быстрого просмотра большого ассортимента.', 'ytdynamics-catalog-compact', 'thumbnails'],
            ['Строки', 'Три независимые зоны: изображение, информация и управление товаром.', 'ytdynamics-catalog-list', 'list'],
            ['Прайс', 'Табличная плотность на десктопе и карточки с подписями ячеек на мобильном.', 'ytdynamics-catalog-price', 'table'],
        ];

        $cards = [];
        foreach ($modes as [$title, $description, $alias, $icon]) {
            $cards[] = $this->node('rmgrid_item', [
                'panel_style' => 'card-default',
                'panel_padding' => 'default',
                'name' => $title,
            ], [
                $this->node('icon', ['icon' => $icon, 'icon_width' => 48, 'icon_color' => 'primary']),
                $this->node('headline', [
                    'content' => $title,
                    'title_element' => 'h2',
                    'title_style' => 'h3',
                    'margin_top' => 'small',
                ]),
                $this->node('text', ['content' => $description, 'margin_top' => 'small']),
                $this->button('Открыть стенд', '/index.php/' . $alias, 'primary'),
            ]);
        }

        // The same four compositions are also mounted on one page and gated
        // by ProductListState. RM Toolbar changes the persisted layout and a
        // reload renders only the selected Builder tree, matching a real
        // category page without shipping four hidden catalogues to the DOM.
        $tile = $this->tileCatalogue();
        $tile[0]['props']['mode'] = 'radicalmart_tile';
        $compact = $this->compactCatalogue();
        $compact[0]['props']['mode'] = 'radicalmart_compact';
        $list = $this->listCatalogue();
        $list[0]['props']['mode'] = 'radicalmart_list';
        $price = $this->priceCatalogue();
        $price[0]['props']['mode'] = 'radicalmart_price';

        return $this->layout([
            $this->hero(
                'Четыре каталога из одних и тех же элементов',
                'Каждое представление — самостоятельная Builder-композиция. В карточках нет зашитой раскладки.'
            ),
            $this->section('Выберите представление', [
                $this->node('rmgrid', [
                    'mode' => 'default',
                    'grid_column_gap' => 'medium',
                    'grid_row_gap' => 'medium',
                    'grid_default' => '1',
                    'grid_small' => '2',
                    'grid_large' => '4',
                ], $cards),
            ]),
            $this->section('Интерактивный каталог', array_merge([
                $this->node('rmordering', [
                    'ordering_width' => 'medium',
                    'margin_bottom' => 'small',
                ]),
                $this->node('rmlayoutswitcher', [
                    'show_grid_button' => true,
                    'show_compact_button' => true,
                    'show_list_button' => true,
                    'show_table_button' => true,
                    'switcher_style' => 'icon_text',
                    'switcher_breakpoint' => 's',
                    'margin_bottom' => 'large',
                ]),
            ], $tile, $compact, $list, $price), 'muted', 'default'),
        ]);
    }

    private function modeLayout(string $title, string $description, array $catalogue): array
    {
        return $this->layout([
            $this->hero($title, $description),
            $this->section('', array_merge([$this->modeNavigation()], $catalogue), 'muted', 'default'),
        ]);
    }

    private function tileCatalogue(): array
    {
        $cards = [];
        foreach ($this->products as $product) {
            $cards[] = $this->node('rmgrid_item', [
                'panel_style' => 'card-default',
                'panel_padding' => 'default',
                'name' => $product['title'],
            ], [$this->productCard((int) $product['id'], (string) $product['category_title'], 'tile')]);
        }

        return [$this->node('rmgrid', [
            'mode' => 'default',
            'grid_column_gap' => 'medium',
            'grid_row_gap' => 'medium',
            'grid_default' => '1',
            'grid_small' => '2',
            'grid_large' => '3',
            'filter' => false,
        ], $cards)];
    }

    private function compactCatalogue(): array
    {
        $cards = [];
        foreach ($this->products as $product) {
            $id = (int) $product['id'];
            $cards[] = $this->node('rmgrid_item', [
                'panel_style' => 'card-default',
                'panel_padding' => 'small',
                'name' => $product['title'],
            ], [
                $this->node('rmproductcard', ['product_id' => $id], [
                    $this->node('rmproductcard_main', [], [
                        $this->node('rmproductfield', [
                            'product_id' => $id,
                            'field' => 'image',
                            'link_product' => true,
                            'image_ratio' => '4/3',
                            'image_fit' => 'contain',
                            'image_loading' => 'lazy',
                        ]),
                        $this->node('text', [
                            'content' => $product['category_title'],
                            'text_style' => 'meta',
                            'margin_top' => 'small',
                        ]),
                        $this->node('rmproductfield', [
                            'product_id' => $id,
                            'field' => 'title',
                            'link_product' => true,
                            'title_element' => 'h3',
                            'title_style' => 'h5',
                            'margin_top' => 'small',
                        ]),
                        $this->node('rmproductfield', [
                            'product_id' => $id,
                            'field' => 'price',
                            'text_style' => 'lead',
                            'show_base_price' => true,
                            'show_discount' => true,
                            'margin_top' => 'small',
                        ]),
                        $this->node('rmproductfield', [
                            'product_id' => $id,
                            'field' => 'availability',
                            'text_style' => 'small',
                            'margin_top' => 'small',
                        ]),
                        $this->node('rmbuy', [
                            'product_id' => $id,
                            'label' => 'В корзину',
                            'button_style' => 'primary',
                            'button_size' => 'small',
                            'show_count' => false,
                            'fullwidth' => true,
                            'margin_top' => 'small',
                        ]),
                        $this->node('rmquickview', [
                            'product_id' => $id,
                            'label' => 'Быстрый просмотр',
                            'button_style' => 'text',
                            'button_size' => 'small',
                            'modal_size' => 'container',
                            'fullwidth' => true,
                            'margin_top' => 'small',
                        ]),
                    ]),
                ]),
            ]);
        }

        return [$this->node('rmgrid', [
            'mode' => 'default',
            'grid_column_gap' => 'small',
            'grid_row_gap' => 'small',
            'grid_default' => '2',
            'grid_small' => '3',
            'grid_medium' => '4',
            'grid_large' => '5',
            'filter' => false,
        ], $cards)];
    }

    private function listCatalogue(): array
    {
        $cards = [];
        foreach ($this->products as $product) {
            $id = (int) $product['id'];
            $cards[] = $this->node('rmgrid_item', [
                'panel_style' => 'card-default',
                'panel_padding' => 'default',
                'name' => $product['title'],
            ], [
                $this->node('rmproductcard', ['product_id' => $id], [
                    $this->node('rmproductcard_main', [], [
                        $this->row([
                            $this->column([
                                $this->node('rmproductfield', [
                                    'product_id' => $id,
                                    'field' => 'image',
                                    'link_product' => true,
                                    'image_ratio' => '4/3',
                                    'image_fit' => 'contain',
                                    'image_loading' => 'lazy',
                                ]),
                            ], ['width_medium' => '1-4']),
                            $this->column([
                                $this->node('text', ['content' => $product['category_title'], 'text_style' => 'meta']),
                                $this->node('rmproductfield', [
                                    'product_id' => $id,
                                    'field' => 'title',
                                    'link_product' => true,
                                    'title_element' => 'h2',
                                    'title_style' => 'h3',
                                    'margin_top' => 'small',
                                ]),
                                $this->node('rmproductfield', [
                                    'product_id' => $id,
                                    'field' => 'description',
                                    'margin_top' => 'small',
                                ]),
                                $this->node('rmproductspecifications', [
                                    'product_id' => $id,
                                    'layout' => 'description-list',
                                    'show_fieldset_titles' => false,
                                    'show_variant_fields' => false,
                                    'divider' => true,
                                    'margin_top' => 'small',
                                ]),
                            ], ['width_medium' => '1-2']),
                            $this->column([
                                $this->node('rmproductfield', [
                                    'product_id' => $id,
                                    'field' => 'price',
                                    'text_style' => 'large',
                                    'show_base_price' => true,
                                    'show_discount' => true,
                                ]),
                                $this->node('rmproductfield', [
                                    'product_id' => $id,
                                    'field' => 'availability',
                                    'margin_top' => 'small',
                                ]),
                                $this->variants($id, 'select'),
                                $this->node('rmbuy', [
                                    'product_id' => $id,
                                    'label' => 'В корзину',
                                    'button_style' => 'primary',
                                    'show_count' => true,
                                    'mobile_stack' => true,
                                    'fullwidth' => true,
                                    'margin_top' => 'small',
                                ]),
                                $this->node('rmquickview', [
                                    'product_id' => $id,
                                    'label' => 'Быстрый просмотр',
                                    'button_style' => 'text',
                                    'modal_size' => 'container',
                                    'fullwidth' => true,
                                    'margin_top' => 'small',
                                ]),
                            ], ['width_medium' => '1-4']),
                        ], ['column_gap' => 'medium', 'row_gap' => 'medium', 'vertical_align' => 'middle']),
                    ]),
                ]),
            ]);
        }

        return [$this->node('rmgrid', [
            'mode' => 'default',
            'grid_column_gap' => 'medium',
            'grid_row_gap' => 'medium',
            'grid_default' => '1',
            'grid_small' => '1',
            'grid_medium' => '1',
            'grid_large' => '1',
            'grid_xlarge' => '1',
            'filter' => false,
        ], $cards)];
    }

    private function priceCatalogue(): array
    {
        $header = $this->node('rmtable_item', ['row_type' => 'head', 'name' => 'Заголовок'], [
            $this->tableCell('Товар', 'Товар', ['cell_type' => 'header', 'scope' => 'col', 'cell_width' => 'expand']),
            $this->tableCell('Артикул', 'Артикул', ['cell_type' => 'header', 'scope' => 'col', 'cell_width' => 'small']),
            $this->tableCell('Цена', 'Цена', ['cell_type' => 'header', 'scope' => 'col', 'cell_width' => 'small']),
            $this->tableCell('Наличие', 'Наличие', ['cell_type' => 'header', 'scope' => 'col', 'cell_width' => 'small']),
            $this->tableCell('Действие', 'Действие', ['cell_type' => 'header', 'scope' => 'col', 'cell_width' => 'medium']),
        ]);

        $rows = [$header];
        foreach ($this->products as $product) {
            $id = (int) $product['id'];
            $rows[] = $this->node('rmtable_item', [
                'row_type' => 'body',
                'row_aria_label' => $product['title'],
                'name' => $product['title'],
            ], [
                $this->tableCell('', 'Товар', [
                    'cell_type' => 'header',
                    'scope' => 'row',
                    'mobile_behavior' => 'full',
                    'mobile_label_position' => 'hidden',
                ], [
                    $this->row([
                        $this->column([
                            $this->node('rmproductfield', [
                                'product_id' => $id,
                                'field' => 'image',
                                'link_product' => true,
                                'image_ratio' => '1/1',
                                'image_fit' => 'contain',
                                'image_height' => '72px',
                                'image_loading' => 'lazy',
                            ]),
                        ], ['width' => 'auto']),
                        $this->column([
                            $this->node('text', ['content' => $product['category_title'], 'text_style' => 'meta']),
                            $this->node('rmproductfield', [
                                'product_id' => $id,
                                'field' => 'title',
                                'link_product' => true,
                                'title_element' => 'h3',
                                'title_style' => 'h5',
                                'margin_top' => 'small',
                            ]),
                        ], ['width' => 'expand']),
                    ], ['column_gap' => 'small', 'row_gap' => 'small', 'vertical_align' => 'middle']),
                ]),
                $this->tableCell('', 'Артикул', ['wrap_mode' => 'nowrap'], [
                    $this->node('rmproductfield', ['product_id' => $id, 'field' => 'code', 'text_style' => 'meta']),
                ]),
                $this->tableCell('', 'Цена', ['wrap_mode' => 'nowrap'], [
                    $this->node('rmproductfield', [
                        'product_id' => $id,
                        'field' => 'price',
                        'text_style' => 'lead',
                        'show_base_price' => true,
                        // The compact price cell keeps the crossed-out base
                        // price, but omits the separate discount badge. The
                        // badge would force a horizontal overflow in the
                        // 320–390px mobile card layout.
                        'show_discount' => false,
                    ]),
                ]),
                $this->tableCell('', 'Наличие', ['wrap_mode' => 'nowrap'], [
                    $this->node('rmproductfield', ['product_id' => $id, 'field' => 'availability', 'text_style' => 'small']),
                ]),
                $this->tableCell('', 'Действие', [
                    'mobile_behavior' => 'full',
                    'mobile_label_position' => 'hidden',
                    'mobile_order' => 'last',
                ], [
                    $this->node('rmbuy', [
                        'product_id' => $id,
                        'label' => 'В корзину',
                        'button_style' => 'primary',
                        'button_size' => 'small',
                        'show_count' => false,
                        'fullwidth' => true,
                    ]),
                    $this->node('rmquickview', [
                        'product_id' => $id,
                        'label' => 'Быстрый просмотр',
                        'button_style' => 'text',
                        'button_size' => 'small',
                        'modal_size' => 'container',
                        'fullwidth' => true,
                        'margin_top' => 'small',
                    ]),
                ]),
            ]);
        }

        return [$this->node('rmtable', [
            'caption' => 'Тестовый прайс-каталог',
            'caption_visibility' => 'screen-reader',
            'table_style' => 'divider',
            'table_size' => 'small',
            'table_hover' => true,
            'table_vertical_align' => 'middle',
            'container_style' => 'default',
            'container_size' => 'small',
            'container_border' => true,
            'container_radius' => true,
            'container_shadow' => 'small',
            'responsive_mode' => 'cards',
            'responsive_breakpoint' => 'm',
            'mobile_label_position' => 'left',
            'mobile_card_style' => 'default',
            'mobile_card_gap' => 'small',
            'mobile_card_padding' => 'small',
            'sticky_header' => true,
            'sticky_first' => false,
        ], $rows)];
    }

    private function productCard(int $id, string $category, string $mode): array
    {
        $main = $this->node('rmproductcard_main', [], [
            $this->node('rmproductfield', [
                'product_id' => $id,
                'field' => 'image',
                'link_product' => true,
                'image_ratio' => '4/3',
                'image_fit' => 'contain',
                'image_loading' => 'lazy',
            ]),
            $this->node('text', ['content' => $category, 'text_style' => 'meta', 'margin_top' => 'small']),
            $this->node('rmproductfield', [
                'product_id' => $id,
                'field' => 'title',
                'link_product' => true,
                'title_element' => 'h3',
                'title_style' => 'h4',
                'margin_top' => 'small',
            ]),
            $this->node('rmproductfield', [
                'product_id' => $id,
                'field' => 'price',
                'text_style' => 'large',
                'show_base_price' => true,
                'show_discount' => true,
                'margin_top' => 'small',
            ]),
            $this->node('rmproductfield', [
                'product_id' => $id,
                'field' => 'availability',
                'margin_top' => 'small',
            ]),
        ]);

        $dropdown = $this->node('rmproductcard_dropdown', [
            'display_mode' => $mode === 'tile' ? 'hover' : 'default',
            'hover_breakpoint' => 'm',
            'panel_style' => 'default',
            'panel_padding' => 'small',
            'show_divider' => false,
            'max_height' => 680,
        ], [
            $this->variants($id, 'buttons'),
            $this->node('rmbuy', [
                'product_id' => $id,
                'label' => 'В корзину',
                'button_style' => 'primary',
                'button_size' => 'small',
                'show_count' => false,
                'fullwidth' => true,
                'margin_top' => 'small',
            ]),
            $this->node('rmquickview', [
                'product_id' => $id,
                'label' => 'Быстрый просмотр',
                'button_style' => 'text',
                'button_size' => 'small',
                'modal_size' => 'container',
                'fullwidth' => true,
                'margin_top' => 'small',
            ]),
        ]);

        return $this->node('rmproductcard', ['product_id' => $id], [$main, $dropdown]);
    }

    private function variants(int $id, string $style): array
    {
        return $this->node('rmvariantselector', [
            'product_id' => $id,
            'variant_fields' => ['catalog-color', 'catalog-size', 'catalog-edition'],
            'style' => $style,
            'action' => 'ajax',
            'button_style' => 'default',
            'image_fit' => 'contain',
            'show_labels' => true,
            'show_selected_value' => true,
            'disable_unavailable' => true,
            'update_url' => 'none',
            'margin_top' => 'small',
        ]);
    }

    private function modeNavigation(): array
    {
        return $this->node('button', ['margin_bottom' => 'large'], [
            $this->node('button_item', ['content' => 'Обзор', 'link' => '/index.php/ytdynamics-catalog-layouts', 'button_style' => 'text']),
            $this->node('button_item', ['content' => 'Плитка', 'link' => '/index.php/ytdynamics-catalog-tile', 'button_style' => 'default']),
            $this->node('button_item', ['content' => 'Компактно', 'link' => '/index.php/ytdynamics-catalog-compact', 'button_style' => 'default']),
            $this->node('button_item', ['content' => 'Строки', 'link' => '/index.php/ytdynamics-catalog-list', 'button_style' => 'default']),
            $this->node('button_item', ['content' => 'Прайс', 'link' => '/index.php/ytdynamics-catalog-price', 'button_style' => 'default']),
        ]);
    }

    private function hero(string $title, string $description): array
    {
        return $this->section('', [
            $this->node('text', ['content' => 'YTDYNAMICS · CATALOG COMPOSITION', 'text_style' => 'meta']),
            $this->node('headline', [
                'content' => $title,
                'title_element' => 'h1',
                'title_style' => 'heading-small',
                'margin_top' => 'small',
            ]),
            $this->node('text', ['content' => $description, 'text_style' => 'lead', 'margin_top' => 'small']),
        ], 'default', 'small');
    }

    private function section(
        string $title,
        array $children,
        string $style = 'default',
        string $padding = 'default'
    ): array {
        if ($title !== '') {
            array_unshift($children, $this->node('headline', [
                'content' => $title,
                'title_element' => 'h2',
                'title_style' => 'h2',
                'margin_bottom' => 'medium',
            ]));
        }

        return $this->node('section', ['style' => $style, 'padding' => $padding, 'width' => 'default'], [
            $this->row([$this->column($children, ['width_medium' => '1-1'])]),
        ]);
    }

    private function layout(array $sections): array
    {
        return ['type' => 'layout', 'children' => $sections, 'version' => '5.0.42'];
    }

    private function row(array $columns, array $props = []): array
    {
        return $this->node('row', $props, $columns);
    }

    private function column(array $children, array $props = []): array
    {
        return $this->node('column', $props, $children);
    }

    private function button(string $content, string $link, string $style = 'default'): array
    {
        return $this->node('button', ['margin_top' => 'small'], [
            $this->node('button_item', ['content' => $content, 'link' => $link, 'button_style' => $style]),
        ]);
    }

    private function tableCell(
        string $text,
        string $mobileLabel,
        array $props = [],
        array $children = []
    ): array {
        return $this->node('rmtable_cell', array_merge([
            'text' => $text,
            'mobile_label' => $mobileLabel,
            'cell_type' => 'auto',
            'scope' => 'auto',
            'mobile_behavior' => 'show',
        ], $props), $children);
    }

    private function node(string $type, array $props = [], array $children = []): array
    {
        $node = ['type' => $type];
        if ($props !== []) {
            $node['props'] = $props;
        }
        if ($children !== []) {
            $node['children'] = $children;
        }

        return $node;
    }

    private function upsertArticle(string $alias, string $title, array $layout): int
    {
        $id = (int) ($this->value('SELECT id FROM joom_content WHERE alias = ?', [$alias]) ?: 0);
        $data = [
            'title' => $title,
            'alias' => $alias,
            'introtext' => '<p>Generated YTDynamics catalogue composition demo.</p>',
            'fulltext' => '<!-- ' . $this->json($layout) . ' -->',
            'state' => 1,
            'catid' => self::ARTICLE_CATEGORY_ID,
            'modified' => $this->now,
            'modified_by' => self::CREATED_BY,
            'images' => '{}',
            'urls' => '{}',
            'attribs' => '{}',
            'metakey' => '',
            'metadesc' => 'YTDynamics Builder catalogue mode demo',
            'access' => 1,
            'metadata' => '{}',
            'featured' => 0,
            'language' => '*',
            'note' => 'Generated by tools/seed-catalog-mode-demos.php',
        ];
        if ($id > 0) {
            $this->update('joom_content', $data, 'id = ?', [$id]);
            return $id;
        }

        $data += [
            'asset_id' => 0,
            'created' => $this->now,
            'created_by' => self::CREATED_BY,
            'created_by_alias' => '',
            'checked_out' => null,
            'checked_out_time' => null,
            'publish_up' => $this->now,
            'publish_down' => null,
            'version' => 1,
            'ordering' => 0,
            'hits' => 0,
        ];

        return $this->insert('joom_content', $data);
    }

    private function upsertMenu(string $alias, string $title, int $articleId): void
    {
        $id = (int) ($this->value('SELECT id FROM joom_menu WHERE alias = ?', [$alias]) ?: 0);
        $componentId = (int) $this->value(
            "SELECT extension_id FROM joom_extensions WHERE element = 'com_content' AND type = 'component'"
        );
        $data = [
            'menutype' => 'mainmenu',
            'title' => $title,
            'alias' => $alias,
            'note' => 'Generated catalogue mode demo',
            'path' => $alias,
            'link' => 'index.php?option=com_content&view=article&id=' . $articleId,
            'type' => 'component',
            'published' => 1,
            'parent_id' => 1,
            'level' => 1,
            'component_id' => $componentId,
            'checked_out' => null,
            'checked_out_time' => null,
            'browserNav' => 0,
            'access' => 1,
            'img' => '',
            'template_style_id' => 0,
            'params' => '{}',
            'home' => 0,
            'language' => '*',
            'client_id' => 0,
            'publish_up' => null,
            'publish_down' => null,
        ];
        if ($id > 0) {
            $this->update('joom_menu', $data, 'id = ?', [$id]);
            return;
        }

        $right = (int) $this->value("SELECT COALESCE(MAX(rgt), 1) FROM joom_menu WHERE menutype = 'mainmenu'");
        $data['lft'] = $right + 1;
        $data['rgt'] = $right + 2;
        $this->insert('joom_menu', $data);
    }

    private function json(mixed $value): string
    {
        return json_encode($value, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR);
    }

    private function query(string $sql, array $params = []): PDOStatement
    {
        $statement = $this->db->prepare($sql);
        $statement->execute(array_values($params));
        return $statement;
    }

    private function value(string $sql, array $params = []): mixed
    {
        return $this->query($sql, $params)->fetchColumn();
    }

    private function insert(string $table, array $data): int
    {
        $columns = array_keys($data);
        $marks = implode(',', array_fill(0, count($columns), '?'));
        $sql = sprintf('INSERT INTO %s (`%s`) VALUES (%s)', $table, implode('`,`', $columns), $marks);
        $this->query($sql, array_values($data));
        return (int) $this->db->lastInsertId();
    }

    private function update(string $table, array $data, string $where, array $whereParams = []): void
    {
        $assignments = implode(', ', array_map(
            static fn(string $column): string => "`{$column}` = ?",
            array_keys($data)
        ));
        $this->query(
            "UPDATE {$table} SET {$assignments} WHERE {$where}",
            array_merge(array_values($data), $whereParams)
        );
    }
}

(new CatalogModeDemoSeeder())->run();
